### PR TITLE
Script for requirements

### PR DESCRIPTION
**Pull request by mo1ein**
Script for Install requirements . It's better than a text file.

### CODE REVIEW

**Comment by lnxpy** [comment]
Thanks for your PR :)

Gonna be great to use a bash script instead of a raw file to install every single package that a project needs. What about other platforms? Are Windows users able to build it up? What about Mac users?
pip package manager is able to maneuver on the raw text files. Here is an example of that.

```shell
Install Options:
  -r, --requirement <file>    Install from the given requirements file. This
                              option can be used multiple times.
  -c, --constraint <file>     Constrain versions using the given constraints
                              file. This option can be used multiple times.
```
In the case that you mentioned, only the Linux-based machines (those who have access to a bash-like CLI) can install the `requirements.sh` and others should pull out the list and install them by themselves.

Best wishes,
Stay safe. :heart: :)

**Comment by mo1ein** [comment]
Yeah you're right. Unfortunately some people are using windows but It's better to use scripts. You can use ```setup.py``` or something like that for install requirements instead of ```.txt``` file

**Comment by debian44** [comment]
As far as I know every supported version of Windows has Power Shell 2.0 by default you can do this on Windows using Power Shell. you can use chocolately with powershell which is an apt-like package manager for Windows or do it by powershel cmdlets

Also using Windows isn't unfotunate at all. Its not the best but its kinda even better than Unix-like OSs in something like Desktop experience

**Comment by lnxpy** [comment]
Pip has it itself. :)
Basic purpose: You need to have python3 installed in order to work with Turbo. Once you've done that, you will have pip installed too.
pip allows you to install any kind of requirements as smooth as possible. Very quick and simple. (as the blockcode I send here)
No pain you gain. :)

So, why would you struggle with a plenty of bash script lines in order to achieve what you would get in a more simple way? 🍕😋

Thanks ❤️ :)
Stay safe pals.

**Pull request closed without merging**
